name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Type check (mobile & server)
        run: npm run typecheck

      - name: Run API tests
        run: npm run test:api
